#!/usr/bin/env python3

import argparse

def readFile(filePath):
    lines = []
    with open(filePath, "r", -1, "utf-8") as file_:
        for line in file_:
            lines.append(line)
    return lines

def dotToDots(filePath):
    currentNode = 0
    nodeNamesMap = {}
    lines = readFile(filePath)
    for line in lines:
        line = line.strip()
        fields = line.split("\"")
        if len(fields) > 1:
            fullNames = fields[1].split("_")
            nodeName = fullNames[0]
            if not nodeName in nodeNamesMap.keys():
                newNodeName = "node_" + str(currentNode)
                currentNode = currentNode + 1
                nodeNamesMap[nodeName] = newNodeName
            keys = nodeNamesMap.keys()
            for key in keys:
                line = line.replace(key, nodeNamesMap[key])
        print (line)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', 
        help = 'Input file',
        type = str,
        required=True)
    args = parser.parse_args()
    filePath = args.f

    dotToDots(filePath)
